-- Archive the 2025-season MatchData/MatchDataUploaded tables (264 rows each, event
-- 2025cafr) under a *2025 suffix, preserving all data and identity/sequence state via
-- true renames rather than drop+recreate. Then create fresh MatchData/MatchDataUploaded
-- tables matching the 2026 match-scouting-form schema.
--
-- NOTE: this migration was applied by hand against the linked remote database (see
-- session history) because `supabase db diff` was diffing against a stale cached
-- catalog and would otherwise have generated destructive DROP COLUMN statements
-- against the live 264-row tables. This file exists to keep migration history and
-- prod.sql declarative source in sync with what was actually applied.

ALTER TABLE "public"."MatchData" RENAME TO "MatchData2025";
ALTER TABLE "public"."MatchDataUploaded" RENAME TO "MatchDataUploaded2025";

ALTER SEQUENCE "public"."MatchData_id_seq" RENAME TO "MatchData2025_id_seq";
ALTER SEQUENCE "public"."MatchDataUploaded_id_seq" RENAME TO "MatchDataUploaded2025_id_seq";

ALTER TABLE "public"."MatchData2025" RENAME CONSTRAINT "MatchData_pkey" TO "MatchData2025_pkey";
ALTER TABLE "public"."MatchDataUploaded2025" RENAME CONSTRAINT "MatchDataUploaded_pkey" TO "MatchDataUploaded2025_pkey";

-- RLS, existing policies, and grants all carry over automatically through the
-- renames above (they're attached to the table's OID, not its name) — only the
-- comments need to be (re)set explicitly.
COMMENT ON TABLE "public"."MatchData2025" IS 'Archived 2025-season match scouting data (2025cafr). Superseded by the 2026 MatchData schema.';
COMMENT ON TABLE "public"."MatchDataUploaded2025" IS 'Archived 2025-season match scouting data (2025cafr). Superseded by the 2026 MatchDataUploaded schema.';

-- The archive is read-only going forward — drop the write policies that carried
-- over from the pre-rename MatchDataUploaded table.
DROP POLICY "Enable insert for authenticated users only" ON "public"."MatchDataUploaded2025";
DROP POLICY "Enable update for authenticated users only" ON "public"."MatchDataUploaded2025";

CREATE TABLE "public"."MatchData" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "event" "text",
    "prematch_scout_name" "text" NOT NULL,
    "prematch_match_number" smallint NOT NULL,
    "prematch_team_number" smallint NOT NULL,
    "prematch_alliance" "text",
    "prematch_noshow" boolean DEFAULT false,
    "postmatch_cards" "text",
    "postmatch_comments" "text"
);
ALTER TABLE "public"."MatchData" OWNER TO "postgres";
ALTER TABLE ONLY "public"."MatchData" ADD CONSTRAINT "MatchData_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."MatchData" ENABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE "public"."MatchData" TO "anon";
GRANT ALL ON TABLE "public"."MatchData" TO "authenticated";
GRANT ALL ON TABLE "public"."MatchData" TO "service_role";
GRANT ALL ON SEQUENCE "public"."MatchData_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."MatchData_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."MatchData_id_seq" TO "service_role";
CREATE POLICY "Enable read access for logged in users" ON "public"."MatchData" FOR SELECT TO "authenticated" USING (true);

CREATE TABLE "public"."MatchDataUploaded" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "event" "text",
    "prematch_scout_name" "text" NOT NULL,
    "prematch_match_number" smallint NOT NULL,
    "prematch_team_number" smallint NOT NULL,
    "prematch_alliance" "text",
    "prematch_noshow" boolean DEFAULT false,
    "postmatch_cards" "text",
    "postmatch_comments" "text",
    "key" "text",
    "source" "text"
);
ALTER TABLE "public"."MatchDataUploaded" OWNER TO "postgres";
COMMENT ON TABLE "public"."MatchDataUploaded" IS 'This is a duplicate of MatchData';
ALTER TABLE ONLY "public"."MatchDataUploaded" ADD CONSTRAINT "MatchDataUploaded_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."MatchDataUploaded" ADD CONSTRAINT "MatchDataUploaded_key_key" UNIQUE ("key");
ALTER TABLE "public"."MatchDataUploaded" ENABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE "public"."MatchDataUploaded" TO "anon";
GRANT ALL ON TABLE "public"."MatchDataUploaded" TO "authenticated";
GRANT ALL ON TABLE "public"."MatchDataUploaded" TO "service_role";
GRANT ALL ON SEQUENCE "public"."MatchDataUploaded_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."MatchDataUploaded_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."MatchDataUploaded_id_seq" TO "service_role";
CREATE POLICY "Enable insert for authenticated users only" ON "public"."MatchDataUploaded" FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "Enable read access for authenticated users" ON "public"."MatchDataUploaded" FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Enable update for authenticated users only" ON "public"."MatchDataUploaded" FOR UPDATE TO "authenticated" USING (true);
