-- Pre-scouting data (issue #51) — teams researched before the event (e.g.
-- via Statbotics), separate from in-person pit scouting. Mirrors PitData's
-- structure/RLS exactly.
CREATE TABLE IF NOT EXISTS "public"."PreScoutData" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "event" "text",
    "scouted_by" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "prescout_team_number" smallint NOT NULL,
    "prescout_epa" real,
    "prescout_archetype" "text",
    "prescout_tier" "text",
    "prescout_comments" "text"
);

ALTER TABLE "public"."PreScoutData" OWNER TO "postgres";

ALTER TABLE "public"."PreScoutData" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."PreScoutData_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."PreScoutData"
    ADD CONSTRAINT "PreScoutData_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."PreScoutData"
    ADD CONSTRAINT "PreScoutData_scouted_by_fkey" FOREIGN KEY ("scouted_by") REFERENCES "public"."User"("user_id");

ALTER TABLE "public"."PreScoutData" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable insert for authenticated users only" ON "public"."PreScoutData" FOR INSERT TO "authenticated" WITH CHECK (("scouted_by" = "auth"."uid"()));

CREATE POLICY "Enable read access for logged in users" ON "public"."PreScoutData" FOR SELECT TO "authenticated" USING (true);

CREATE POLICY "Enable update for authenticated users only" ON "public"."PreScoutData" FOR UPDATE TO "authenticated" USING (true);

GRANT ALL ON TABLE "public"."PreScoutData" TO "anon";
GRANT ALL ON TABLE "public"."PreScoutData" TO "authenticated";
GRANT ALL ON TABLE "public"."PreScoutData" TO "service_role";

GRANT ALL ON SEQUENCE "public"."PreScoutData_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."PreScoutData_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."PreScoutData_id_seq" TO "service_role";
