-- Split pre-scouting comments into their own per-scout table (issue #60).
-- Previously PreScoutData mixed a single team assessment (epa/archetype/
-- tiers) with a single free-text comment in the same row, so once one scout
-- pre-scouted a team, every other scout's "Edit" button landed on that
-- scout's row too — there was no way to add a second, independent note.
-- Now PreScoutData stays one canonical assessment row per team/event
-- (enforced below), and comments move to PreScoutComment: many rows per
-- team/event, at most one per scout, so each scout can add or edit their
-- own note without touching anyone else's.

CREATE TABLE IF NOT EXISTS "public"."PreScoutComment" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "event" "text",
    "scouted_by" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "prescout_team_number" smallint NOT NULL,
    "comment" "text" NOT NULL
);

ALTER TABLE "public"."PreScoutComment" OWNER TO "postgres";

ALTER TABLE "public"."PreScoutComment" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."PreScoutComment_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."PreScoutComment"
    ADD CONSTRAINT "PreScoutComment_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."PreScoutComment"
    ADD CONSTRAINT "PreScoutComment_scouted_by_fkey" FOREIGN KEY ("scouted_by") REFERENCES "public"."User"("user_id");

ALTER TABLE "public"."PreScoutComment" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable insert for authenticated users only" ON "public"."PreScoutComment" FOR INSERT TO "authenticated" WITH CHECK (("scouted_by" = "auth"."uid"()));

CREATE POLICY "Enable read access for logged in users" ON "public"."PreScoutComment" FOR SELECT TO "authenticated" USING (true);

CREATE POLICY "Enable update for authenticated users only" ON "public"."PreScoutComment" FOR UPDATE TO "authenticated" USING (true);

GRANT ALL ON TABLE "public"."PreScoutComment" TO "anon";
GRANT ALL ON TABLE "public"."PreScoutComment" TO "authenticated";
GRANT ALL ON TABLE "public"."PreScoutComment" TO "service_role";

GRANT ALL ON SEQUENCE "public"."PreScoutComment_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."PreScoutComment_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."PreScoutComment_id_seq" TO "service_role";

-- At most one comment per scout per team/event.
CREATE UNIQUE INDEX "prescout_comment_scout_unique" ON "public"."PreScoutComment" USING "btree" ("event", "prescout_team_number", "scouted_by");

-- Carry over any existing free-text prescout_comments before dropping the column.
INSERT INTO "public"."PreScoutComment" ("event", "scouted_by", "prescout_team_number", "comment", "created_at")
SELECT "event", "scouted_by", "prescout_team_number", "prescout_comments", "created_at"
FROM "public"."PreScoutData"
WHERE "prescout_comments" IS NOT NULL AND "prescout_comments" != '';

ALTER TABLE "public"."PreScoutData" DROP COLUMN "prescout_comments";

-- One canonical prescouting assessment per team/event.
CREATE UNIQUE INDEX "prescout_data_team_unique" ON "public"."PreScoutData" USING "btree" ("event", "prescout_team_number");
